<a href="https://colab.research.google.com/github/xorToja/data-science-bootcamp/blob/master/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.18.5'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [ ]:
x = np.array([1,3])
x
print(x)
type(x)

[1 3]


numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape # wyświetli tuple z liczbą elementów dla kazdego wymiaru

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.3, 2.3, 1.4])

In [ ]:
x.dtype

dtype('float64')

2D Array

In [ ]:
x = np.array([[1,2], [-3, 1]])
print(x)

[[ 1  2]
 [-3  1]]


In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x = np.array([[1,2,4],[4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [ ]:
x.shape

(2, 3)

3D Array

In [ ]:
x = np.array(
   [[[4,3,1],
     [3,1,2]],

     [[4,1,3],
      [4,2,1]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape # (2,2,3)
# dwie tablice
# dwa wiersze
# trzy kolumny


(2, 2, 3)

# Typy danych

In [ ]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [ ]:
A = np.array([1.0, 2.3, 3.3])
A.dtype

dtype('float64')

In [ ]:
A = np.array([1,2,3], dtype = 'float')
A.dtype

dtype('float64')

In [ ]:
A = np.array([1,2,3], dtype = 'complex')
A.dtype

dtype('complex128')

In [ ]:
A = np.array([1.0, 2.7, 3.3], dtype = 'int')
A.dtype

dtype('int64')

In [ ]:
A

array([1, 2, 3])

In [ ]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [ ]:
A = np.array([24, 120, 230], dtype = np.int8)
A.dtype

dtype('int8')

In [ ]:
A = np.array([24, 120, 230], dtype = np.uint8)
A.dtype # 0 - 255

dtype('uint8')

# Tworzenie tablic

In [3]:
np.zeros(shape = (4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [4]:
np.zeros(shape = (4, 10), dtype = 'int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [5]:
np.ones(shape = (4, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [6]:
np.full(shape = (3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(start = 5, stop = 10)

array([5, 6, 7, 8, 9])

In [10]:
np.arange(start = 10, stop = 100, step = 10)


array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [12]:
np.arange(start = 100, stop = 10, step = -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [13]:
np.linspace(start = 0, stop = 1, num = 10) # zamiast podawac step, podajemy ile ma byc elementow

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [15]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
A.reshape((3,5))
A.reshape((3, -1)) # jak wstawisz -1 to python automatycznie dobierze odpowiedni rozmiar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# Podstawowe operacje na tablicach

In [17]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])

print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [18]:
A + B

array([6, 0, 7, 4])

In [28]:
np.add(A, B)

array([6, 0, 7, 4])

In [19]:
A - B

array([0, 2, 1, 0])

In [27]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [20]:
A * B

array([ 9, -1, 12,  4])

In [26]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [21]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [29]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [22]:
A + 3

array([6, 4, 7, 5])

In [23]:
2 * A

array([6, 2, 8, 4])

In [24]:
A + 3 * B

array([12, -2, 13,  8])

In [32]:
X = np.array([[1, 2], [-2, 0]])
Y = np.array([[6,0], [-1, 2]])

print(X, "\n")
print(Y)

[[ 1  2]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [33]:
X * Y # nie jest mnożeniem macierzowym!

array([[6, 0],
       [2, 0]])

In [34]:
np.dot(X, Y) # natomiast to już tak

array([[  4,   4],
       [-12,   0]])

In [35]:
X.dot(Y) # =/= Y.dot(X)

array([[  4,   4],
       [-12,   0]])

# Generowanie liczb pseudolosowych

In [36]:
np.random.seed(0) # ziarno losowania

In [37]:
np.random.randn() # losowy rozkład normalny

1.764052345967664

In [38]:
np.random.randn(10) # wylosuje 10 liczb

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [39]:
np.random.randn(10, 4) # 10 liczb w tablicy z 4 kolumnami

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [40]:
np.random.rand() # z przedziału 0-1 bez jedynki!

0.1965823616800535

In [41]:
np.random.rand(10) # to jak wyżej

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [42]:
np.random.rand(10, 4) # jak wyżej

array([[0.03918779, 0.28280696, 0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318, 0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145, 0.26538949, 0.52324805],
       [0.09394051, 0.5759465 , 0.9292962 , 0.31856895],
       [0.66741038, 0.13179786, 0.7163272 , 0.28940609],
       [0.18319136, 0.58651293, 0.02010755, 0.82894003],
       [0.00469548, 0.67781654, 0.27000797, 0.73519402],
       [0.96218855, 0.24875314, 0.57615733, 0.59204193],
       [0.57225191, 0.22308163, 0.95274901, 0.44712538],
       [0.84640867, 0.69947928, 0.29743695, 0.81379782]])

In [43]:
np.random.randint(10) # 0 - 10 bez 10

8

In [44]:
np.random.randint(low = 10, high = 101) # liczby z zakresu 10 do 100

26

In [45]:
np.random.randint(low = 10, high = 100, size = 10)

array([34, 39, 31, 35, 90, 70, 71, 93, 43, 42])

In [46]:
np.random.choice([4,2,1,3,5]) # losowa liczba z listy

5

In [47]:
np. random.choice(['python', 'sql', 'java'])

'sql'

In [49]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.random.shuffle(data) # przetasuje dane w miejscu
data

array([0, 2, 4, 6, 3, 7, 1, 9, 5, 8])

# Podstawowe funkcje

In [53]:
np.exp(1)

2.718281828459045

In [54]:
np.sqrt(4)

2.0

In [55]:
np.all([2, 3, 1]) # sprawdza czy kazdy element zwraca True (i daje True), lub chociaz jeden zwraca False (i zwroci False)

True

In [56]:
np.any([0,0,0])

False

In [57]:
np.any([0,1,0]) # analogicznie, jakikolwiek True

True

In [58]:
bool(1.3)

True

In [60]:
A = np.random.rand(5)
A

array([0.7142413 , 0.99884701, 0.1494483 , 0.86812606, 0.16249293])

In [61]:
np.argmax(A) # zwraca indeks najwiekszej wartosci

1

In [62]:
A[np.argmax(A)]

0.9988470065678665

In [63]:
np.argmin(A)

2

In [64]:
np.argsort(A) # zwróci posorotwaną rosnąco tablicę po indeksach

array([2, 4, 0, 3, 1])

In [65]:
np.max(A)

0.9988470065678665

In [66]:
np.min(A)

0.14944830465799375

In [67]:
np.mean(A)

0.5786311205639121

In [68]:
np.median(A)

0.7142412995491114

In [69]:
np.std(A)

0.3566925031879748

# Indeksowanie, Wycinanie

In [70]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [71]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [72]:
A[2]

2

In [73]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [74]:
A[:3]

array([0, 1, 2])

In [75]:
A[[0,2]] # konkretne elementy

array([0, 2])

In [76]:
A[-1]

19

In [77]:
A[10:15]

array([10, 11, 12, 13, 14])

In [78]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [79]:
A[:, 0] # wycinamy w ten sposób kolumnę o indeksie 0

array([ 0,  5, 10, 15])

In [80]:
A[:, -1]

array([ 4,  9, 14, 19])

In [81]:
A[1:3, 2] # z wierszy o indeksach od 1 do 2!!!! wycinam kolumnę o indeksie 2

array([ 7, 12])

In [82]:
A[0:3,]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [83]:
A[1,2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# Iteracja po tablicach

In [84]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [85]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [86]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [87]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


# Zmiana rozmiaru tablic

In [88]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [90]:
A.shape

(4, 5)

In [91]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [92]:
A.ravel() # postać jednowymiarowa

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [93]:
A.T # transpozycja

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

# Maski Logiczne

In [94]:
A = np.arange(start = -10, stop = 10, step = 0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [95]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [96]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [99]:
# ale A[A > 5 and A < 5] nie zadziała, trzeba użyć funkcji bitwise_and()
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [100]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [101]:
np.bitwise_or(A < 5, A > -5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])