<a href="https://colab.research.google.com/github/xorToja/data-science-bootcamp/blob/master/07_uczenie_glebokie/02_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 2.x
import tensorflow as tf
import numpy as np
import pandas as pd
import plotly.express as px
tf.__version__

'2.3.0'

# Wprowadzenie - pierwszy model


Model sekwencyjny to nic innego jak liniowy stos warstw

In [9]:
# utworzenie instancji Sequential
from tensorflow.keras.models import Sequential

model = Sequential()
print(model)

Podstawowym elementem składowym modelu są warstwy. Aby dodać najbardziej standardową warstwę - warstwę gęsto połączoną należy użyć warstwy **Dense**. Aby dodać warstwę do modelu nalezy użyć metody .add()

In [10]:
from tensorflow.keras.layers import Dense
model.add(Dense(units = 4, input_shape=(10,))) # 4 neurony, wejście to 10 zmiennych (trzeba to dodać w pierwszej warstwie)

Wyświetlenie podsumowania modelu: metoda .summary()

In [11]:
model.summary() # (10 + 1) * 4

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 4)                 44        
Total params: 44
Trainable params: 44
Non-trainable params: 0
_________________________________________________________________


Dodanie kolejnej warstwy

In [14]:
model.add(Dense(units = 2))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 4)                 44        
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 10        
Total params: 54
Trainable params: 54
Non-trainable params: 0
_________________________________________________________________


# Funkcje aktywacji
Istotnym elementem sieci neuronowych jest dobór odpowiednich funkcji aktywacji. Funkcje aktywacji jak sama nazwa wskazuje są odpowiedzialne za aktywowanie odpowiednich neuronów podczas procesu uczenia.

Jeżeli nie określimy podczas dodawania warstwy funkcji aktywacji, domyślnie stosowana jest liniowa funkcja aktywacji, tzn a(x) = x.

Warstwa z liniową funkcją aktywacji może uczyć się tylko liniowych przekształceń danych wejściowych. Dlatego stosuje się różne funkcje aktywacji aby rozwiązywać problemy nieliniowe.

In [15]:
from tensorflow.keras.activations import linear

random_data = np.linspace(start = -3, stop = 3, num = 300)
data = pd.DataFrame({'data' : random_data, 'linear' : linear(random_data)})
data.head()

data    linear
0 -3.000000 -3.000000
1 -2.979933 -2.979933
2 -2.959866 -2.959866
3 -2.939799 -2.939799
4 -2.919732 -2.919732

In [17]:
px.line(data, x = 'data', y = 'linear', width = 500, height = 400, range_y = [-3, 3])

In [18]:
from tensorflow.keras.activations import sigmoid

data = pd.DataFrame({'data' : random_data, 'sigmoid' : sigmoid(random_data)})
data.head()

data   sigmoid
0 -3.000000  0.047426
1 -2.979933  0.048341
2 -2.959866  0.049272
3 -2.939799  0.050221
4 -2.919732  0.051187

In [21]:
px.line(data, x = 'data', y = 'sigmoid', width = 500, height = 400, range_y = [-0.5, 1.5])

In [22]:
from tensorflow.keras.activations import relu # zamienia ujemne na zera, a reszte zostawia bez zmian

data = pd.DataFrame({'data' : random_data, 'relu' : relu(random_data)})
data.head()

data  relu
0 -3.000000   0.0
1 -2.979933   0.0
2 -2.959866   0.0
3 -2.939799   0.0
4 -2.919732   0.0

In [23]:
px.line(data, x = 'data', y = 'relu', width = 500, height = 400, range_y = [-0.5, 1.5])

In [24]:
from tensorflow.keras.activations import tanh # tangens hiperboliczny - przyjmuje wartości z przezdiału -1; 1

data = pd.DataFrame({'data' : random_data, 'tanh' : tanh(random_data)})
data.head()

data      tanh
0 -3.000000 -0.995055
1 -2.979933 -0.994853
2 -2.959866 -0.994643
3 -2.939799 -0.994424
4 -2.919732 -0.994196

In [25]:
px.line(data, x = 'data', y = 'tanh', width = 500, height = 400, range_y = [-1.5, 1.5])

In [26]:
model = Sequential()
model.add(Dense(units = 8, activation='relu', input_shape = (10,)))
model.add(Dense(units = 1, activation='sigmoid'))
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 8)                 88        
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 9         
Total params: 97
Trainable params: 97
Non-trainable params: 0
_________________________________________________________________


# Kompilacja modelu
Przed rozpoczęciem trenowania sieci należy odpowiednio skonfigurować proces uczenia. W tym celu określamy: 

*   rodzaj optymalizatora
*   funkcję straty
*   metryki, które będziemy obserwować podczas trenowania sieci



In [ ]:
# klasyfikacja binarna
model.compile(optimizer='rmsprop',
              loss= 'binary_crossentropy',
              metrics=['accuracy'])

# klasyfikacja wieloklasowa
model.compile(optimizer='rmsprop',
              loss= 'categorical_crossentropy',
              metrics=['accuracy'])

# regresja
model.compile(optimizer='rmsprop',
              loss= 'mse')


### <a name='a3'></a>Trenowanie modelu
Za dane wejściowe do modelu należy przekazać Numpy arrays:
* **epochs** - krotność przejścia danych przez sieć w procesie uczenia
* **batch_size** - rozmiar wsadu po którym następuje aktualizacja wag
* **validation_split** - część danych treningowych, które zostaną wykorzystane jako zbiór walidacyjny # jest optymalny
* **validation_data** - (x_val, y_val) - dane wykorzystane do walidacji modelu

In [ ]:
# model.fit(data, labels, epochs=10, batch_size=32)
# model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)
# model.fit(data, labels, epochs=10, batch_size=32, validation_data=(x_val, y_val))

### <a name='a4'></a> Przykład - klasyfikacja binarna

In [27]:
data = np.random.randn(10000, 150)
labels = np.random.randint(2, size=(10000, 1))

print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [ ]:
data[:3]

In [ ]:
labels[:10]

In [30]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid')) # ostatnia warstwa ma jeden neuron, bo klasyfikujemy binarnie (do jednej z dwóch klas)
# dlatego też wykorzystuję w tym przypadku klasę aktywacji sigmoid

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20)

Epoch 1/20
313/313 [==============================] - 0s 983us/step - loss: 0.7492 - accuracy: 0.5014
Epoch 2/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6961 - accuracy: 0.5395
Epoch 3/20
313/313 [==============================] - 0s 984us/step - loss: 0.6785 - accuracy: 0.5675
Epoch 4/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6651 - accuracy: 0.5914
Epoch 5/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6519 - accuracy: 0.6169
Epoch 6/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6383 - accuracy: 0.6395
Epoch 7/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6244 - accuracy: 0.6587
Epoch 8/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6096 - accuracy: 0.6726
Epoch 9/20
313/313 [==============================] - 0s 1ms/step - loss: 0.5959 - accuracy: 0.6896
Epoch 10/20
313/313 [==============================] - 0s 1ms/step - loss: 0.5807 - accuracy: 0.

In [31]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=64) # szybciej się będzie trenował, bo aktualizujemy wagi nie co (standardowe) 32 próby a co 64

Epoch 1/20
157/157 [==============================] - 0s 1ms/step - loss: 0.7586 - accuracy: 0.4906
Epoch 2/20
157/157 [==============================] - 0s 1ms/step - loss: 0.7034 - accuracy: 0.5262
Epoch 3/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6854 - accuracy: 0.5594
Epoch 4/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6736 - accuracy: 0.5807
Epoch 5/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6632 - accuracy: 0.6004
Epoch 6/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6534 - accuracy: 0.6152
Epoch 7/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6434 - accuracy: 0.6304
Epoch 8/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6327 - accuracy: 0.6470
Epoch 9/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6227 - accuracy: 0.6651
Epoch 10/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6112 - accuracy: 0.6777

In [32]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2)
# w tym wypadku na zbiorze walidacyjnym będą o wiele gorsze wyniki niż na zbiorze uczacym
# bo dane sa wygenerowane losowo

Epoch 1/20
250/250 [==============================] - 0s 2ms/step - loss: 0.7680 - accuracy: 0.4916 - val_loss: 0.7219 - val_accuracy: 0.5105
Epoch 2/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6999 - accuracy: 0.5387 - val_loss: 0.7174 - val_accuracy: 0.5080
Epoch 3/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6788 - accuracy: 0.5690 - val_loss: 0.7205 - val_accuracy: 0.5025
Epoch 4/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6631 - accuracy: 0.6014 - val_loss: 0.7239 - val_accuracy: 0.4950
Epoch 5/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6485 - accuracy: 0.6205 - val_loss: 0.7317 - val_accuracy: 0.4860
Epoch 6/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6344 - accuracy: 0.6451 - val_loss: 0.7387 - val_accuracy: 0.4850
Epoch 7/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6188 - accuracy: 0.6653 - val_loss: 0.7453 - val_accuracy: 0.4925
Epoch 

In [33]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=0)

In [34]:
metrics = history.history
metrics.keys()

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])

In [36]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/20
250/250 [==============================] - 1s 2ms/step - loss: 0.7866 - accuracy: 0.5036 - val_loss: 0.7348 - val_accuracy: 0.4875
Epoch 2/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6957 - accuracy: 0.5493 - val_loss: 0.7314 - val_accuracy: 0.4890
Epoch 3/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6730 - accuracy: 0.5803 - val_loss: 0.7322 - val_accuracy: 0.4875
Epoch 4/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6568 - accuracy: 0.6047 - val_loss: 0.7331 - val_accuracy: 0.4935
Epoch 5/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6414 - accuracy: 0.6315 - val_loss: 0.7383 - val_accuracy: 0.4910
Epoch 6/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6264 - accuracy: 0.6570 - val_loss: 0.7449 - val_accuracy: 0.5005
Epoch 7/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6108 - accuracy: 0.6755 - val_loss: 0.7517 - val_accuracy: 0.4895
Epoch 

In [37]:
test_data = np.random.randn(5, 150)
test_labels = np.random.randint(2, size=(5, 1))

In [38]:
model.predict(test_data)

array([[0.02337137],
       [0.86480093],
       [0.10754815],
       [0.8789274 ],
       [0.34612125]], dtype=float32)

In [39]:
model.predict_proba(test_data)

Instructions for updating:
Please use `model.predict()` instead.


array([[0.02337137],
       [0.86480093],
       [0.10754815],
       [0.8789274 ],
       [0.34612125]], dtype=float32)

In [40]:
model.predict_classes(test_data)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


array([[0],
       [1],
       [0],
       [1],
       [0]], dtype=int32)

### <a name='a5'></a> Przykład - klasyfikacja wieloklasowa


In [41]:
data = np.random.random((10000, 150))
labels = np.random.randint(10, size=(10000, 1))

In [42]:
print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [43]:
labels[:10]

array([[4],
       [4],
       [5],
       [3],
       [0],
       [4],
       [9],
       [9],
       [8],
       [2]])

In [44]:
from tensorflow.keras.utils import to_categorical
labels = to_categorical(labels, num_classes=10)  # jak to działa? a no ustawia jedynkę w miejscu w którym znajduje się indeks klasy
# tzn. jeżeli pierwszy obiekt ma klasę 2 (czyli 3 indeks jeżeli zaczynamy od 0)
# to będzie dla niej [0, 0, 1, 0, ...]
# dla klasy 1 byłoby [0, 1, 0, 0, ...]
labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [45]:
labels[1]

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.], dtype=float32)

In [46]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=10, activation='softmax')) # dodane 10 bo tyle klas mamy
# i nie sigmoid tylko softmax

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, batch_size=32, epochs=30, validation_split=0.2)

Epoch 1/30
250/250 [==============================] - 0s 2ms/step - loss: 2.3162 - accuracy: 0.1047 - val_loss: 2.3045 - val_accuracy: 0.0970
Epoch 2/30
250/250 [==============================] - 0s 1ms/step - loss: 2.3027 - accuracy: 0.1116 - val_loss: 2.3044 - val_accuracy: 0.1000
Epoch 3/30
250/250 [==============================] - 0s 1ms/step - loss: 2.3013 - accuracy: 0.1104 - val_loss: 2.3048 - val_accuracy: 0.1030
Epoch 4/30
250/250 [==============================] - 0s 1ms/step - loss: 2.2990 - accuracy: 0.1210 - val_loss: 2.3127 - val_accuracy: 0.0945
Epoch 5/30
250/250 [==============================] - 0s 1ms/step - loss: 2.2963 - accuracy: 0.1213 - val_loss: 2.3126 - val_accuracy: 0.0950
Epoch 6/30
250/250 [==============================] - 0s 1ms/step - loss: 2.2921 - accuracy: 0.1177 - val_loss: 2.3095 - val_accuracy: 0.1020
Epoch 7/30
250/250 [==============================] - 0s 1ms/step - loss: 2.2888 - accuracy: 0.1265 - val_loss: 2.3162 - val_accuracy: 0.0960
Epoch 

In [47]:
test_data = np.random.random((10, 150))

model.predict(test_data)

array([[0.11247379, 0.12005936, 0.08243975, 0.02889047, 0.29808053,
        0.13095722, 0.05501522, 0.08610214, 0.06016568, 0.02581586],
       [0.08091205, 0.11536675, 0.1259287 , 0.1030835 , 0.06909677,
        0.08757998, 0.09393007, 0.07883836, 0.16990954, 0.07535429],
       [0.10946984, 0.05596216, 0.18151183, 0.13271075, 0.08159336,
        0.11664364, 0.06626631, 0.07445055, 0.14031248, 0.04107904],
       [0.09094812, 0.07720467, 0.09332443, 0.12449923, 0.0830623 ,
        0.1404753 , 0.14177558, 0.10441293, 0.08992519, 0.0543723 ],
       [0.06247378, 0.09328659, 0.0805792 , 0.13663623, 0.12187277,
        0.11807117, 0.1376852 , 0.07233616, 0.09079192, 0.08626702],
       [0.1551137 , 0.11232727, 0.11652456, 0.03647806, 0.15198761,
        0.03555321, 0.09349264, 0.13657522, 0.06928199, 0.09266567],
       [0.10491776, 0.05123891, 0.2074573 , 0.03350807, 0.10091022,
        0.08025559, 0.1421661 , 0.15022998, 0.07531497, 0.05400122],
       [0.06469341, 0.11754195, 0.1089123

In [48]:
model.predict_classes(test_data)

array([4, 8, 2, 6, 6, 0, 2, 5, 6, 4])

### <a name='a6'></a> Przykład - regresja

In [49]:
data = np.random.random((10000, 150))
labels = 50 * np.random.random(10000)

In [50]:
labels[:10]

array([24.52999035, 28.86118177, 17.35297903, 13.91227248, 33.29401231,
       42.86617033, 45.23255679, 46.94870689, 36.5924074 ,  2.37527505])

In [51]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mse')

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
250/250 [==============================] - 0s 2ms/step - loss: 269.9207 - val_loss: 204.7469
Epoch 2/30
250/250 [==============================] - 0s 1ms/step - loss: 207.4689 - val_loss: 207.9702
Epoch 3/30
250/250 [==============================] - 0s 1ms/step - loss: 207.0963 - val_loss: 205.1981
Epoch 4/30
250/250 [==============================] - 0s 1ms/step - loss: 206.9606 - val_loss: 205.3913
Epoch 5/30
250/250 [==============================] - 0s 1ms/step - loss: 206.4942 - val_loss: 206.6807
Epoch 6/30
250/250 [==============================] - 0s 1ms/step - loss: 206.4261 - val_loss: 205.5727
Epoch 7/30
250/250 [==============================] - 0s 1ms/step - loss: 206.0283 - val_loss: 205.5583
Epoch 8/30
250/250 [==============================] - 0s 1ms/step - loss: 205.5980 - val_loss: 206.8142
Epoch 9/30
250/250 [==============================] - 0s 1ms/step - loss: 205.4336 - val_loss: 207.2387
Epoch 10/30
250/250 [==============================] - 0s 1ms/st

In [52]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mae',
              metrics=['mse'])

model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 13.4735 - mse: 259.9029 - val_loss: 12.3885 - val_mse: 205.9210
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 12.4154 - mse: 207.8875 - val_loss: 12.3863 - val_mse: 205.7384
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 12.4034 - mse: 207.4814 - val_loss: 12.3963 - val_mse: 206.1676
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 12.3927 - mse: 207.2762 - val_loss: 12.3871 - val_mse: 205.6522
Epoch 5/10
250/250 [==============================] - 0s 1ms/step - loss: 12.3768 - mse: 206.8258 - val_loss: 12.3946 - val_mse: 205.8561
Epoch 6/10
250/250 [==============================] - 0s 1ms/step - loss: 12.3580 - mse: 206.9114 - val_loss: 12.4034 - val_mse: 206.1988
Epoch 7/10
250/250 [==============================] - 0s 1ms/step - loss: 12.3585 - mse: 206.4943 - val_loss: 12.4185 - val_mse: 206.9594
Epoch 8/10
250/250 [==============

In [53]:
test_data = np.random.random((10, 150))

model.predict(test_data)

array([[25.538414],
       [26.635685],
       [27.976913],
       [27.25639 ],
       [25.8916  ],
       [23.120413],
       [23.051811],
       [24.217993],
       [23.455809],
       [27.130592]], dtype=float32)